In [1]:
#Importing Dependencies

import nltk
import string
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
# Taking the Input

name = input('Enter the Company Name:')

Enter the Company Name:Ynot


In [3]:
voc_size=50

In [4]:
# The assignment consists of several company Names and they are taken into a csv file 
# The CSV file is then loaded into the program using pandas module


import pandas as pd

book = pd.read_csv('book.csv')

book.head()

book = book.drop(['S.no'], axis = 1)

book.head()

Company Name
0  Guvi Geek Networks Private Limited
1                         Maximl Labs
2          Pur Energy Private Limited
3                      Agnikul Cosmos
4                  The ePlane Company

In [5]:
list_company = book['Company Name']

In [6]:
list_company

0       Guvi Geek Networks Private Limited
1                              Maximl Labs
2               Pur Energy Private Limited
3                           Agnikul Cosmos
4                       The ePlane Company
5         PYTORQ Solutions Private Limited
6                      Bigphi Technologies
7             Ather Energy Private Limited
8     Rekindle Automations Private Limited
9     Aerostrovilos Energy Private Limited
10                    Impensus Electronics
11                           Doodhbhandaar
12                                 Swapeco
13         Statlogic India Private Limited
14                     YNOS Venture Engine
Name: Company Name, dtype: object

In [7]:
import numpy as np

list_np = np.array(list_company, dtype= list)

list_np

array(['Guvi Geek Networks Private Limited', 'Maximl Labs',
       'Pur Energy Private Limited', 'Agnikul Cosmos',
       'The ePlane Company', 'PYTORQ Solutions Private Limited',
       'Bigphi Technologies', 'Ather Energy Private Limited',
       'Rekindle Automations Private Limited',
       'Aerostrovilos Energy Private Limited', 'Impensus Electronics',
       'Doodhbhandaar', 'Swapeco', 'Statlogic India Private Limited',
       'YNOS Venture Engine'], dtype=object)

In [8]:
# Converting the Data Frame into a array of type String

list_np = list_np.astype(str)

In [9]:
list_np

array(['Guvi Geek Networks Private Limited', 'Maximl Labs',
       'Pur Energy Private Limited', 'Agnikul Cosmos',
       'The ePlane Company', 'PYTORQ Solutions Private Limited',
       'Bigphi Technologies', 'Ather Energy Private Limited',
       'Rekindle Automations Private Limited',
       'Aerostrovilos Energy Private Limited', 'Impensus Electronics',
       'Doodhbhandaar', 'Swapeco', 'Statlogic India Private Limited',
       'YNOS Venture Engine'], dtype='<U36')

In [10]:
# tfidf_vectorizer = TfidfVectorizer(stop_words='english')
# tfidf_matrix = tfidf_vectorizer.fit_transform(list_np)

# tfidf_matrix.shape

In [11]:
# print(tfidf_matrix)

In [12]:
# # Cosine Similarity 


# from sklearn.metrics.pairwise import cosine_similarity


# for   
# cosine_similarity(feature_vec_1.reshape(1, -1), feature_vec_2.reshape(1, -1))[0][0]

In [13]:
# from nltk.tokenize import word_tokenize

In [14]:
# Importing Porter Stemmer from NLTK library to stem the sentences
# importing re library to perform data preprocessing

from nltk.stem.porter import PorterStemmer
import re
from nltk.corpus import stopwords
ps = PorterStemmer()
corpus = []
for i in range(0, len(list_np)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', list_np[i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [15]:
corpus

['guvi geek network privat limit',
 'maximl lab',
 'pur energi privat limit',
 'agnikul cosmo',
 'eplan compani',
 'pytorq solut privat limit',
 'bigphi technolog',
 'ather energi privat limit',
 'rekindl autom privat limit',
 'aerostrovilo energi privat limit',
 'impensu electron',
 'doodhbhandaar',
 'swapeco',
 'statlog india privat limit',
 'yno ventur engin']

In [16]:
# To convert the preprocessed words into a vector one_hot_encoding is performed on the data
# To perform one hot encoding the modules are imported from keras library

from tensorflow.keras.preprocessing.text import one_hot
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[20, 28, 23, 21, 10],
 [29, 9],
 [7, 43, 21, 10],
 [32, 45],
 [13, 20],
 [49, 37, 21, 10],
 [9, 9],
 [9, 43, 21, 10],
 [24, 4, 21, 10],
 [35, 43, 21, 10],
 [32, 1],
 [4],
 [39],
 [5, 5, 21, 10],
 [23, 27, 31]]

In [17]:
# Padding is perfomed as a part of data pre processing

from tensorflow.keras.preprocessing.sequence import pad_sequences
sent_length=10
embedded = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded)

[[ 0  0  0  0  0 20 28 23 21 10]
 [ 0  0  0  0  0  0  0  0 29  9]
 [ 0  0  0  0  0  0  7 43 21 10]
 [ 0  0  0  0  0  0  0  0 32 45]
 [ 0  0  0  0  0  0  0  0 13 20]
 [ 0  0  0  0  0  0 49 37 21 10]
 [ 0  0  0  0  0  0  0  0  9  9]
 [ 0  0  0  0  0  0  9 43 21 10]
 [ 0  0  0  0  0  0 24  4 21 10]
 [ 0  0  0  0  0  0 35 43 21 10]
 [ 0  0  0  0  0  0  0  0 32  1]
 [ 0  0  0  0  0  0  0  0  0  4]
 [ 0  0  0  0  0  0  0  0  0 39]
 [ 0  0  0  0  0  0  5  5 21 10]
 [ 0  0  0  0  0  0  0 23 27 31]]


In [18]:
# The input string has also needs to go through data pre processing to convert into vectorized form

name_onehot = [one_hot(name,voc_size)] 
name_onehot

[[19]]

In [19]:
name_pad = pad_sequences(name_onehot,padding='pre',maxlen=sent_length)
print(name_pad)

[[ 0  0  0  0  0  0  0  0  0 19]]


In [20]:
# The cosine similarity is performed on the data pre processed

# The results are printed below

from sklearn.metrics.pairwise import cosine_similarity  

for x in range(0,len(embedded)):
    print(list_np[x], ':',cosine_similarity(embedded[x].reshape(1, -1), name_pad.reshape(1, -1))[0][0])
    
# The obtained results are not satisfactory since the Cosine Similarity is 0.65 which is not the highest among the other results

Guvi Geek Networks Private Limited : 0.21063136593556733
Maximl Labs : 0.2963992148724529
Pur Energy Private Limited : 0.20248557974359568
Agnikul Cosmos : 0.8149553245687551
The ePlane Company : 0.838443616300637
PYTORQ Solutions Private Limited : 0.15230388746165127
Bigphi Technologies : 0.7071067811865476
Ather Energy Private Limited : 0.20117019055664215
Rekindle Automations Private Limited : 0.29708795551115325
Aerostrovilos Energy Private Limited : 0.1663205257599714
Impensus Electronics : 0.031234752377721213
Doodhbhandaar : 1.0
Swapeco : 1.0
Statlogic India Private Limited : 0.4113450348948635
YNOS Venture Engine : 0.6580865923618391


In [21]:
# print(corpus)
# print(corpus[1])
# print(corpus[1].split())

['guvi geek network privat limit', 'maximl lab', 'pur energi privat limit', 'agnikul cosmo', 'eplan compani', 'pytorq solut privat limit', 'bigphi technolog', 'ather energi privat limit', 'rekindl autom privat limit', 'aerostrovilo energi privat limit', 'impensu electron', 'doodhbhandaar', 'swapeco', 'statlog india privat limit', 'yno ventur engin']
maximl lab
['maximl', 'lab']


In [22]:
# TO obtain neccessary results another approach is being taken 
# levenshtein distance is being taken as criteria to obtain the similarity between the words 
# the input word is compared with each word of each sentences.
# The edit_distance alias levenshtein distance is being calculate and are shown below

score = 100
res = {}

for x in range(0,len(corpus)):
    for j in corpus[x].split():
        print(j,'\t',nltk.edit_distance(j,name))
        distance = nltk.edit_distance(j,name)
        if score > distance:
            score = distance
            res = {list_np[x]: distance}
            final = list_np[x]

guvi 	 4
geek 	 4
network 	 6
privat 	 5
limit 	 4
maximl 	 6
lab 	 4
pur 	 4
energi 	 5
privat 	 5
limit 	 4
agnikul 	 6
cosmo 	 5
eplan 	 5
compani 	 7
pytorq 	 5
solut 	 4
privat 	 5
limit 	 4
bigphi 	 6
technolog 	 7
ather 	 5
energi 	 5
privat 	 5
limit 	 4
rekindl 	 6
autom 	 4
privat 	 5
limit 	 4
aerostrovilo 	 10
energi 	 5
privat 	 5
limit 	 4
impensu 	 6
electron 	 7
doodhbhandaar 	 12
swapeco 	 7
statlog 	 6
india 	 4
privat 	 5
limit 	 4
yno 	 2
ventur 	 5
engin 	 4


In [23]:
# The least Score is taken as the neccesary result.

res


{'YNOS Venture Engine': 2}

In [24]:
final

'YNOS Venture Engine'

In [25]:
print('The Search results are:',final )

The Search results are: YNOS Venture Engine
